---
title: "Introdução ao HTML"
author: "Jeanne Franco"
format: html
editor: visual
date: 08/05/2023
lang: pt
---

## Introdução

Uma página web é capaz de interpretar um código HTML e renderizá-lo de forma compreensível para o leitor exibindo textos, botões, abas, etc. através das configurações das tags dessa linguagem de marcação. Atualmente o HTML encontra-se na versão 5.

## Estrutura básica de uma página em HTML

Abaixo no código estão apresentados as principais tags utilizadas para produzir um documento HTML e para que eles seja corretamente interpretado pelos browsers.

``` r
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>Document</title>
</head>
<body>
<!-- Conteúdo -->
</body>
</html>
```

**Linha 1:** a instrução `DOCTYPE` deve ser a primeira a aparecer no código para indicar a versão do HTML, neste caso usamos a versão atual HTML5.

**Linhas 2 e 10:** todo código HTML deve ter a abertura e o fechamento, portanto, abrimos o código com `<html>` e fechamos com `</html>`. Todas as demais tags ficam dentro desse espaço.

**Linhas 3 e 6:** abertura e fechamento da tag `head` que define o cabeçalho do documento. O conteúdo nesse espaço não é visualizado no browser, apenas contém instruções do seu conteúdo. Dentro dessa tag podem ser definidos o estilo do documento e o script.

**Linha 4:** a tag `meta` especifica o conjunto de caracteres que serão usados para renderizar o texto da página. O UTF-8 contém todos os caracteres dos padrões Unicode e ASCII, sendo, portanto, o mais utilizado.

**Linha 5:** a tag `title` define o título da página. Ele aparecerá na janela/aba do navegador.

**Linhas 7 e 9:** abertura e fechamento da tag `body`, no qual será apresentado todo o conteúdo da página no browser. Nesse intervalo ficarão as tags que representam os títulos, textos, botões, etc.

**Linha 8:** essa linha apresenta a sintaxe que pode ser usada para adição de comentários, ele não aparecerá no browser.

```         
!-- Conteúdo -->
```

Para desenvolver páginas com conteúdo HTML podem ser usados editores de texto como bloco de notas do Windows, Nano e Emacs do Linux. Outros editores mais avançados com sintaxe highlight e autocomplete também são usados e auxiliam nos códigos os tornando mais fáceis de serem compreendidos, como exemplos tem os Sublime Text, Atom, Brackets, RStudio e Visual Studio Code.

## Tags do HTML

As tags de um documento HTML são representadas por nomes específicos que aparecem entre os sinais `<` e `>`. Algumas tags precisam ser abertas e fechadas, ao ser fechada é necessário utilizar uma barra, por exemplo, `</body>`. A tag `meta` não precisa ser fechada.

## Cabeçalhos do HTML

Os cabeçalhos são usados para identificar páginas e seções, eles possuem aparência diferenciada do restante do texto. Há seis níveis de cabeçalhos/títulos que são usados pelas tags `h1`, `h2`, `h3`, `h4`, `h5` e `h6`.

::: {.callout-note appearance="simple"}
De acordo com as regras de SEO, é recomendado que uma página possua apenas uma tag `<h1>` que indique seu assunto, pois essa tag informa aos motores de busca qual sua principal palavra-chave.
:::

Acrescente o seguinte código na linha 8 da primeira listagem desse documento e veja a renderização em um browser.

``` r
<h1>Título de nível 1</h1>
<h2>Título de nível 2</h2>
<h3>Título de nível 3</h3>
<h4>Título de nível 4</h4>
<h5>Título de nível 5</h5>
<h6>Título de nível 6</h6>
```

## Parágrafos do HTML

Os parágrafos em um documento HTML são gerados pelas tags `<p>` e `</p>`. Os parágrafos serão dispostos na tela em forma de blocos um abaixo do outro.

Use o código abaixo e adicione na linha 8 da primeira listagem desse documento.

``` r
<p>Primeiro parágrafo do texto.</p>
<p>Segundo parágrafo do texto.</p>
<p>Terceiro parágrafo do texto.</p>
```

## Imagens no HTML

A inserção de imagens no HTML é feita através da tag `img`, que recebe no atributo `scr` o endereço do arquivo a ser carregado. Outros atributos são o `alt` que apresenta um texto alternativo caso a imagem não seja carregada e o `title` que é mostrado quando colocamos o cursos em cima da imagem.
